### ISSUE TITLE
Why no UK information?

### ISSUE THREAD

**Issue by corinnebosley** [okfde/farmsubsidy.org#2]
Hello, again,
I'm also interested in why I can't find any information on farms in the UK.  Am I just looking in the wrong place or is there a reason?

Thanks

**Comment by pudo** [comment]
The Ukraine is not yet an EU member state. 

Just kidding, you can fetch the data for Great Britain here: 

https://data.farmsubsidy.org/latest/gb_2014.csv.gz
https://data.farmsubsidy.org/latest/gb_2015.csv.gz
https://data.farmsubsidy.org/latest/gb_2016.csv.gz
https://data.farmsubsidy.org/latest/gb_2017.csv.gz

and the older data here:

https://data.farmsubsidy.org/combined/GB_United_Kingdom_1999-2013_C_LR2014-12-19.tar.gz

I assume @stefanw will add the final batch before DataHarvest conference in May :)

**Comment by corinnebosley** [comment]
Awesome, thanks @pudo!

**Comment by stefanw** [comment]
I'll try my best. 😉
